# -*- coding= utf-8 -*-
from odoo import fields, models

class AccountInvoice(models.Model):
    _inherit = 'account.move'
    
    IdRegistroVenta = fields.Char(string="Id Registro Venta")
    Recibo = fields.Char(string="Recibo")
    IdVehiculo = fields.Char(string="IdVehiculo")
    Placa = fields.Char(string="Placa")
    IdTurno = fields.Char(string="IdTurno")
    IdManguera = fields.Char(string="IdManguera")
    HoraInicio = fields.Date(string="HoraInicio")
    HoraFin = fields.Date(string="HoraFin")
    Precio = fields.Char(string="Precio")
    AbonoCredito = fields.Char(string="AbonoCredito")
    Cantidad = fields.Char(string="Cantidad")
    Valor = fields.Char(string="Valor")
    Descuento = fields.Char(string="Descuento")
    Kilometraje = fields.Char(string="Kilometraje")
    Manejo = fields.Char(string="Manejo")
    PorcentajeManejo = fields.Char(string="PorcentajeManejo")
    PrecioCliente = fields.Char(string="PrecioCliente")
    IdCara = fields.Char(string="IdCara")
    IdIsla = fields.Char(string="IdIsla")
    IdSurtidor = fields.Char(string="IdSurtidor")
    IdUnidadMedida = fields.Char(string="IdUnidadMedida")
    IdHistoricoPrecio = fields.Char(string="IdHistoricoPrecio")
    RUTConductor = fields.Char(string="RUTConductor")
    PorcentajeClienteCredito = fields.Char(string="PorcentajeClienteCredito")
    EsDescuentoClienteCredito = fields.Boolean(string="EsDescuentoClienteCredito")
    ValorCambioPrecio = fields.Char(string="ValorCambioPrecio")
    IdEstacion = fields.Char(string="IdEstacion")
    LecturaInicial = fields.Char(string="LecturaInicial")
    LecturaFinal = fields.Char(string="LecturaFinal")
    ROM = fields.Char(string="ROM")
    CodSurtidor = fields.Char(string="CodSurtidor")
    CodCara = fields.Char(string="CodCara")
    Prefijo = fields.Char(string="Prefijo")
    Consecutivo = fields.Char(string="Consecutivo")
    EsAnulado = fields.Boolean(string="EsAnulado")
    FechaProximoMantenimiento = fields.Char(string="FechaProximoMantenimiento")